name: NixOS (nixpkgs stable)

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths: [ "**/nixos-stable.yml" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.05

    - name: Patch flake.nix
      run: sed -i 's/nixos-unstable/nixos-24.05/g' flake.nix

    - name: Update flake.lock
      run: nix flake update

    - name: Build
      run: nix build
